feat: add prototype of ManyToManyRelationJoinStrategy
sqlalchemy-filterset/sqlalchemy-filterset pull request #15
Opened 2024-07-04 21:12 UTC by Mrreadiness

Suggestion to [Issue ](https://github.com/sqlalchemy-filterset/sqlalchemy-filterset/issues/11)

2024-07-10 05:55 UTC, RamiAwar commented on sqlalchemy_filterset/strategies.py
> +        for el in self.chain:
more efficient to use functools.reduce

2024-07-26 21:12 UTC, ymezencev requested changes
We need to add this to the docs

2024-07-26 21:12 UTC, ymezencev commented on tests/strategies/test_join_chain.py
> +        )
Join на MtoM все таки осуждаю)))))
Фильтр по вложенным Join to Join to Join прям классно

2024-07-26 21:12 UTC, ymezencev commented on sqlalchemy_filterset/strategies.py
Maybe rename 
JoinChainStrategy to MultiJoinStrategy
RelationJoinStrategy to JoinStrategy
RelationSubqueryExistsStrategy to ExistsStrategy

as @RamiAwar suggested in https://github.com/sqlalchemy-filterset/sqlalchemy-filterset/issues/11#issuecomment-2219629117

2024-07-27 06:54 UTC, RamiAwar reviewed
lgtm! nice work.

my only comment: should is_outer / is_full be an argument? or its own join type? since it doesn't already exist, we can introduce it however we like.

I think copying sqlalchemy and SQL closely is better as a user experience. When you look at the multi join strategy code you'll more easily understand it if you had JoinStrategy and OuterJoinStrategy (because it resembles written SQL then).

is_full I think can be an argument of OuterJoin on the other hand, but maybe also nicer to be explicit and create another type here too.

2024-07-27 10:09 UTC, Mrreadiness commented
@RamiAwar I thought about different classes but now they look overwhelmed. The current interface is the same as [sqlalchemy](https://docs.sqlalchemy.org/en/14/core/selectable.html#sqlalchemy.sql.expression.Select.join), it's more flexible than classes.

2024-07-27 10:14 UTC, ymezencev approved these changes

2024-07-27 11:14 UTC, RamiAwar commented
Fair point if sqlalchemy also supports this.

Alrightt

2024-07-27 11:14 UTC, RamiAwar approved these changes

2024-07-27 12:22 UTC, ArtemTitorenko approved these changes

2024-07-27 18:03 UTC, merged